all: 
	cd pbdata;\
	make all
	cd hdf;\
	make all
	cd alignment;\
	make all
	
gtest:
	cd pbdata;\
	make gtest
	cd hdf;\
	make gtest
	cd alignment;\
	make gtest

clean:
	cd pbdata;\
	make clean
	cd alignment;\
	make clean 
	cd hdf;\
	make clean
	rm -rf xml

